[package]
name = "groebner_basis"
version = "0.1.0"
authors = ["kyawakyawa <kyawashell@gmail.com>"]
edition = "2018"
default-run = "groebner_basis"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-gmp = "0.5.0"
